---
title: "More about me"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education

**Columbia University Mailman School of Public Health - May 2020** 

_New York, NY_

Master of Public Health (MPH), Department of Environmental Health Sciences, Certificate in Molecular Epidemiology

**Vanderbilt University - May 2018**

_Nashville, TN_

Bachelor of Arts, Double Major in Medicine, Health & Society and Environmental Sociology

**University of Edinburgh - Fall 2017**

_Edinburgh, Scotland_

Semester study abroad


# Professional Experience

**Mount Sinai Hospital, Office of Environmental Health & Safety - Summer 2019**

_Graduate Intern, New York City, NY_

*   Improved worker health and safety by running chemical exposure level tests in labs and analyzing the results

*   Compiled industrial hygiene reports in Excel for six NYC Mount Sinai hospital locations and evaluated standard regulatory limits

*   Provided support on ongoing projects, such as researching the health effects of fiberglass particulates and indoor air quality


**US Department of Health & Human Services, Office of HIV/AIDS & Infectious Disease Policy - Summer 2016**

_Undergraduate Intern, Rosslyn, VA & Washington, D.C._

*   Created and organized comprehensive Excel spreadsheets, sent daily news briefs to the team, and communicated with community partners for AIDS.gov Virtual Office Hours appointments by cold-calling community centers

*   Supported the AIDS.gov team with logistical and administrative tasks for the Int’l AIDS conference in Durban, South Africa

*   Created and presented a Facebook Live Briefing Docket, demonstration, and blog post; helped manage social media content for AIDS.gov; assisted in transcribing Facebook Live conference videos


**Vanderbilt University - Fall 2015 to Spring 2017**

_Resident Advisor, Nashville, TN_

*   Created educational and social programs, provided mentorship, and served as a resource for 30+ residents

*   Collaborated with professional Area Coordinators, Head Residents, faculty, and other campus resources and departments to create a community where students could grow and learn via meaningful programming

*   Performed various administrative responsibilities including paperwork, meetings, trainings, and on call rounds


# Leadership & Involvement 

**Vanderbilt Global Health Case Competition - Spring 2018**

_Vanderbilt Institute for Global Health, Nashville, TN_

*   Competed in a group of four against 12 other teams in Vanderbilt’s Global Health Case Competition; the competition challenge was to provide solutions on how to expand access to emergency medical services in the rural Hinterland region of Guyana


**Student Sustainability Grant Recipient - Spring 2017 to Spring 2018**

_Vanderbilt University, University of Edinburgh, Nashville, TN and Edinburgh, Scotland_

*   Received a $10k grant to install eco-powered gym equipment in Alumni Hall at Vanderbilt University as well as £100 to give away potted herb plants and seedlings at the University of Edinburgh to promote local eating and the slow food movement


**Vanderbilt International Student Relations Co-chair - Fall 2016 to Spring 2017**

_Multicultural Leadership Council, Nashville, TN_ 

*   Organized, planned, and hosted the Lanterns Showcase for international students to share their stories and experiences of studying abroad at an American university; 100+ students attended

*   Served as a resource for a cohort of international students and as the liaison between the Multicultural Leadership Council and the Office of International Student & Scholar Services

*   Led bi-weekly meetings to facilitate engaging dialogue on relevant current issues

**Vanderbilt Residential & Environmental Affairs Committee - Fall 2016 to Spring 2017**

_Vanderbilt Student Government, Nashville, TN_ 

*   Collaborated with administration to develop and implement more environmentally sustainable practices on campus, such as increasing student access to recycling on campus and promoting Green Fund initiatives


# Volunteer Experience

**Student Volunteer - Spring 2016 and Spring 2017** 

_Vanderbilt Alternative Spring Break, White Oak, TN and Memphis, TN_ 

*   Volunteered at multiple sites on issues that included rural healthcare in impoverished areas to pediatric cancer care and treatment


# Languages & Skills 
*   Native fluency in English and Mandarin Chinese, basic proficiency in Japanese

*   Proficient in Microsoft Office: Word, Excel, PowerPoint, Outlook

*   R programming [relevant coursework in Data Science I]

*   GIS mapping software [relevant coursework in Public Health GIS]

*   Adobe Premiere Pro video editing and production software

